/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as PapersPaperIdRouteImport } from './routes/papers/$paperId'
import { Route as NotesNoteIdRouteImport } from './routes/notes/$noteId'
import { Route as PapersPaperIdIndexRouteImport } from './routes/papers/$paperId.index'
import { Route as PapersPaperIdNotesNoteIdRouteImport } from './routes/papers/$paperId.notes.$noteId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersPaperIdRoute = PapersPaperIdRouteImport.update({
  id: '/papers/$paperId',
  path: '/papers/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersPaperIdIndexRoute = PapersPaperIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PapersPaperIdRoute,
} as any)
const PapersPaperIdNotesNoteIdRoute =
  PapersPaperIdNotesNoteIdRouteImport.update({
    id: '/notes/$noteId',
    path: '/notes/$noteId',
    getParentRoute: () => PapersPaperIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/papers/$paperId': typeof PapersPaperIdRouteWithChildren
  '/notes/': typeof NotesIndexRoute
  '/papers/$paperId/': typeof PapersPaperIdIndexRoute
  '/papers/$paperId/notes/$noteId': typeof PapersPaperIdNotesNoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes': typeof NotesIndexRoute
  '/papers/$paperId': typeof PapersPaperIdIndexRoute
  '/papers/$paperId/notes/$noteId': typeof PapersPaperIdNotesNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/papers/$paperId': typeof PapersPaperIdRouteWithChildren
  '/notes/': typeof NotesIndexRoute
  '/papers/$paperId/': typeof PapersPaperIdIndexRoute
  '/papers/$paperId/notes/$noteId': typeof PapersPaperIdNotesNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/notes/$noteId'
    | '/papers/$paperId'
    | '/notes/'
    | '/papers/$paperId/'
    | '/papers/$paperId/notes/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/notes/$noteId'
    | '/notes'
    | '/papers/$paperId'
    | '/papers/$paperId/notes/$noteId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/notes/$noteId'
    | '/papers/$paperId'
    | '/notes/'
    | '/papers/$paperId/'
    | '/papers/$paperId/notes/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  PapersPaperIdRoute: typeof PapersPaperIdRouteWithChildren
  NotesIndexRoute: typeof NotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$paperId': {
      id: '/papers/$paperId'
      path: '/papers/$paperId'
      fullPath: '/papers/$paperId'
      preLoaderRoute: typeof PapersPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$paperId/': {
      id: '/papers/$paperId/'
      path: '/'
      fullPath: '/papers/$paperId/'
      preLoaderRoute: typeof PapersPaperIdIndexRouteImport
      parentRoute: typeof PapersPaperIdRoute
    }
    '/papers/$paperId/notes/$noteId': {
      id: '/papers/$paperId/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/papers/$paperId/notes/$noteId'
      preLoaderRoute: typeof PapersPaperIdNotesNoteIdRouteImport
      parentRoute: typeof PapersPaperIdRoute
    }
  }
}

interface PapersPaperIdRouteChildren {
  PapersPaperIdIndexRoute: typeof PapersPaperIdIndexRoute
  PapersPaperIdNotesNoteIdRoute: typeof PapersPaperIdNotesNoteIdRoute
}

const PapersPaperIdRouteChildren: PapersPaperIdRouteChildren = {
  PapersPaperIdIndexRoute: PapersPaperIdIndexRoute,
  PapersPaperIdNotesNoteIdRoute: PapersPaperIdNotesNoteIdRoute,
}

const PapersPaperIdRouteWithChildren = PapersPaperIdRoute._addFileChildren(
  PapersPaperIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  PapersPaperIdRoute: PapersPaperIdRouteWithChildren,
  NotesIndexRoute: NotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
