import { relations, sql } from "drizzle-orm"
import {
	bigint,
	check,
	index,
	integer,
	jsonb,
	pgTable,
	primaryKey,
	text,
	timestamp,
	unique,
	uuid,
} from "drizzle-orm/pg-core"
import { user } from "./auth"
import { workspaces } from "./workspaces"

export const papers = pgTable(
	"papers",
	{
		id: uuid("id").primaryKey().defaultRandom(),
		ownerUserId: text("owner_user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		contentHash: text("content_hash").notNull(),
		doi: text("doi"),
		arxivId: text("arxiv_id"),
		title: text("title").notNull(),
		authors: jsonb("authors").$type<string[]>(),
		year: integer("year"),
		venue: text("venue"),
		abstract: text("abstract"),
		citationCount: integer("citation_count"),
		pages: text("pages"),
		volume: text("volume"),
		issue: text("issue"),
		publisher: text("publisher"),
		publicationType: text("publication_type"),
		url: text("url"),
		displayFilename: text("display_filename").notNull().default(""),
		fileSizeBytes: bigint("file_size_bytes", { mode: "number" }).notNull(),
		pdfObjectKey: text("pdf_object_key").notNull(),
		blocksObjectKey: text("blocks_object_key"),
		parseStatus: text("parse_status").notNull().default("pending"),
		parseError: text("parse_error"),
		// Live progress reported by MinerU during the `running` state. Both null
		// when no parse has started; populated and updated each poll while
		// state="running"; left in place after `done`/`failed` for the UI.
		parseProgressExtracted: integer("parse_progress_extracted"),
		parseProgressTotal: integer("parse_progress_total"),
		enrichmentStatus: text("enrichment_status").notNull().default("pending"),
		enrichmentSource: text("enrichment_source"),
		enrichedAt: timestamp("enriched_at", { withTimezone: true }),
		// TASK-019: agent-facing per-paper summary. Generated by the
		// paper-summarize worker after parse completes. Read by the
		// agent (TASK-022) at summon time as Layer-2 context. Not shown
		// to users directly. Idempotency keys: re-runs only when the
		// canonical model name or prompt version changes upstream.
		summary: text("summary"),
		summaryStatus: text("summary_status").notNull().default("pending"),
		summaryGeneratedAt: timestamp("summary_generated_at", { withTimezone: true }),
		summaryModel: text("summary_model"),
		summaryPromptVersion: text("summary_prompt_version"),
		summaryError: text("summary_error"),
		metadataEditedByUser: jsonb("metadata_edited_by_user")
			.$type<{
				title?: boolean
				authors?: boolean
				year?: boolean
				doi?: boolean
				arxivId?: boolean
				venue?: boolean
				abstract?: boolean
				pages?: boolean
				volume?: boolean
				issue?: boolean
				publisher?: boolean
				publicationType?: boolean
				url?: boolean
			}>()
			.notNull()
			.default({}),
		metadataCandidates: jsonb("metadata_candidates")
			.$type<
				Array<{
					id: string
					source: string
					queryKind: string
					matchKind: string
					confidence: number
					metadata: unknown
					createdAt: string
				}>
			>()
			.notNull()
			.default([]),
		metadataProvenance: jsonb("metadata_provenance")
			.$type<
				Record<
					string,
					{
						source: string
						queryKind: string
						matchKind: string
						confidence: number
						updatedAt: string
					}
				>
			>()
			.notNull()
			.default({}),
		createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp("updated_at", { withTimezone: true })
			.notNull()
			.defaultNow()
			.$onUpdate(() => new Date()),
		deletedAt: timestamp("deleted_at", { withTimezone: true }),
	},
	(table) => [
		unique("papers_owner_content_hash_unq").on(table.ownerUserId, table.contentHash),
		index("idx_papers_owner_user_id").on(table.ownerUserId),
		index("idx_papers_content_hash").on(table.contentHash),
		check(
			"papers_parse_status_check",
			sql`${table.parseStatus} in ('pending', 'parsing', 'done', 'failed')`,
		),
		check(
			"papers_enrichment_status_check",
			sql`${table.enrichmentStatus} in ('pending', 'enriching', 'enriched', 'partial', 'failed', 'skipped')`,
		),
		check(
			"papers_summary_status_check",
			sql`${table.summaryStatus} in ('pending', 'running', 'done', 'failed', 'no-credentials')`,
		),
	],
)

export const workspacePapers = pgTable(
	"workspace_papers",
	{
		workspaceId: uuid("workspace_id")
			.notNull()
			.references(() => workspaces.id, { onDelete: "cascade" }),
		paperId: uuid("paper_id")
			.notNull()
			.references(() => papers.id, { onDelete: "cascade" }),
		grantedBy: text("granted_by")
			.notNull()
			.references(() => user.id),
		grantedAt: timestamp("granted_at", { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => [
		primaryKey({ name: "workspace_papers_pkey", columns: [table.workspaceId, table.paperId] }),
		index("idx_workspace_papers_workspace_id").on(table.workspaceId),
	],
)

export const papersRelations = relations(papers, ({ many, one }) => ({
	owner: one(user, {
		fields: [papers.ownerUserId],
		references: [user.id],
	}),
	workspaceLinks: many(workspacePapers),
}))

export const workspacePapersRelations = relations(workspacePapers, ({ one }) => ({
	workspace: one(workspaces, {
		fields: [workspacePapers.workspaceId],
		references: [workspaces.id],
	}),
	paper: one(papers, {
		fields: [workspacePapers.paperId],
		references: [papers.id],
	}),
	granter: one(user, {
		fields: [workspacePapers.grantedBy],
		references: [user.id],
	}),
}))

export type Paper = typeof papers.$inferSelect
export type NewPaper = typeof papers.$inferInsert
export type WorkspacePaper = typeof workspacePapers.$inferSelect
